CREATE TABLE creators (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  img VARCHAR(255) NOT NULL,
  date VARCHAR(255) NOT NULL,
  bio VARCHAR(610) NOT NULL,
  hobbies VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL
)

INSERT INTO creators (name, img, date, bio, hobbies, email) VALUES ('Hani Kahale','https://images.ctfassets.net/hbi2916vb08c/3SPQtBPtNnTYSF1PtMw6zq/d1ca2ca21b940cad0730d51aaf3a0507/1683153961830.png', '23 Aug 1995', 'Hani is a highly ambitious and passionate individual who is always striving for personal and professional growth. As an architect, Hani developed a keen eye for detail and a deep appreciation for design. However, due to a strong passion for constant learning and staying up to date with emerging technologies, Hani decided to shift their career into the tech industry.', 'tennis,gym,fitness,cooking', 'hani@cook.ai'), ('Stefan Lemke', 'https://images.ctfassets.net/hbi2916vb08c/7rcteZq8tbUnZiSnlf45jv/0b2a0e3893cdb2d5bf11384f8467cf6d/1682587336886.png', '13 Oct 1983', 'Since 2014, I am an active member of a Berlin-based maker space called "Raumfahrtagentur". Several different topics coming together there, e.g. laser cutting, wood work, 3d printing, electronics, hardware/software development, projection mapping, textile work, prototyping and many more. I have an entrepreneurial mindset and I am interested in: gamification, digital OOH, IoT, smart city, value co-creation, S-D logic, ecosystem business models, civic participation, rapid prototyping.',  'food,rabbithole,gardening', 'stefan@cook.ai'), ('Puritama Toro Benavides', 'https://images.ctfassets.net/hbi2916vb08c/eXLP3xKz21vM5xfmul3E5/f86f72be57cab099f0caa3f4b6fd8032/Ai_Bild_Puri.png', '07 Jul 1993', 'Puritama has a degree in retail sales and years of experience with customer contact and working in a team. However, she has always been enthusiastic about working on a PC. Learning new programs and systems has always been easy for her, new challenges motivate her and she likes to solve problems and optimize processes by finding creative solutions. Therefore, she decided to pursue a career as a programmer and first taught herself programming with the course "CS50: Introduction to Computer Science" at Harvard University. And then continued with a 4-month intensive course "Full Stack Web and App".', 'music,even more music,gaming', 'puri@cook.ai'), ('Miroslav Ljubicic', 'https://images.ctfassets.net/hbi2916vb08c/4ugz7lGrnWeLhTuuC2vNG8/ea520483c12137c3a6b662bbfd66ac03/mrky.jpg', '25 Oct 1981', 'after completing studies for management in information systems, he started working in a printing house as a graphic designer, where he also completed certification for graphic design. After several years of experience, he studied web design and in the following years exclusively deals with HTML, CSS and JavaScript improvement. After several years of experience in this field, decides for Full Stack boot camp within the WBS codding school. Where he is working on this as one of the group projects.', 'cars,computer moding,gaming', 'mrky@cook.ai');